kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: client-nfs-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate 
  template:
    metadata:
      labels:
        app: client-nfs-provisioner
    spec:
      containers:
        - name: client-nfs-provisioner
          image: quay.io/jackieli/client-nfs-provisioner:latest
          volumeMounts:
            - name: client-nfs-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ifs
            - name: NFS_SERVER
              value: 10.10.10.60
            - name: NFS_PATH
              value: /ifs/kubernetes
      volumes:
        - name: client-nfs-root
          nfs:
            server: 10.10.10.60
            path: /ifs/kubernetes